# Generated by Django 5.0 on 2023-12-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='ocean1.jpg', upload_to='post_images/'),
        ),
    ]
