# Generated by Django 5.0 on 2023-12-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_excerpt_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slide_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
