# Generated by Django 5.0 on 2023-12-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slide_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slide_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
